### ISSUE TITLE
Feature: Display Local Weather

### ISSUE THREAD

**Issue by lapinell** [nashvillefcc/local-weather-app#3]
# User Story
As a user, I should be able to see what the current weather is at my current location so that I can prepare properly to go outside.

## Related tasks
- [ ] #13 (UI) Display local temperature statically
- [ ] #28 (JS) Get user coordinates
- [ ] #27 (JS) Display local temperature dynamically
- [ ] #17 (UI) Static weather description
- [ ] #29 (JS) Dynamic weather descriptions
- [ ] #14 (UI) Static location description
- [ ] #30 (JS) Dynamic location descriptions
- [ ] #33 (UI) Styling second pass on local weather feature
